name: practice-workflow
on: 
  push:
    branches:
      - main
jobs:
  echo-jobs:
    runs-on: ubuntu-latest
    name: echo
    steps:
      - name: "echo hello world"
        run: echo "Hello World!"